services:
  postgres:
    image: ankane/pgvector
    ports:
      - 5432:5432

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ai
    expose:
      - 5432:5432

  redis:
    image: redis:7.0.11
    ports:
      - 6379:6379
    expose:
      - 6379:6379